version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"